#apiVersion versi Kubernetes API yang digunakan object
apiVersion: v1
#Jenis object service
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
#spesifikasi dari service yang akan dibuat
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo
    tier: backend