#menggunakan CircleCI versi 2.1
version: 2.1

jobs:
   #membuat job lint-dockerfile
   lint-dockerfile:
      docker:
        #menggunakan docker image latest
        - image: "docker:19.03.15"
      steps:
        #git branch checkout
        - checkout
        #setup remote docker supaya docker bisa berjalan di docker (docker in docker)
        - setup_remote_docker
        #install hadolint dan menjalankannya terhadap berkas dockerfile
        - run:
            name: "Lint Dockerfile"
            command: "docker run --rm --interactive hadolint/hadolint:latest < Dockerfile"
   #membuat job build-app-karsajobs-ui
   build-app-karsajobs-ui:
      docker:
        #menggunakan docker image latest
        - image: "docker:19.03.15"
      steps:
        #git branch checkout
        - checkout
        #setup remote docker supaya docker bisa berjalan di docker (docker in docker)
        - setup_remote_docker
        #build image dari dockerfile
        - run:
            name: "Build Image"
            command: "docker build . -t ghcr.io/tiosetiaatih/karsajobs-ui:latest"
        #Login ke GitHub Packages
        - run:
            name: "Login GitHub Packages"
            command: "docker login ghcr.io -u $GITHUB_USERNAME -p $GITHUB_PASSWORD"
        #Push image ke GitHub Packages
        - run:
            name: "Pushing Image"
            command: "docker push ghcr.io/tiosetiaatih/karsajobs-ui:latest"

workflows:
#job yang di define lint-dockerfile dan build-app-karsajobs-ui (build dan push image)
  lint-build-push-workflow:
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui