version: '2.1'
orbs:
  docker: circleci/docker@2.2.0
workflows:
  lint:
    jobs:
      - docker/hadolint:
          dockerfiles: Dockerfile
          executor-class: medium
          hadolint-tag: karsajobs-ui:latest
          ignore-rules: 'DL4005,DL3008'
          trusted-registries: 'docker.io,my-company.com:5000'
  build-app-karsajobs-ui:
    jobs:
      - docker/publish:
          image: karsajobs-ui:latest
          tag: karsajobs-ui
          update-description: true