#menggunakan CircleCI versi 2.1
version: 2.1

jobs:
   #membuat job lint-dockerfile
   lint-dockerfile:
      docker:
        #menggunakan docker image latest
        - image: "docker:19.03.15"
      steps:
        #git branch checkout
        - checkout
        #setup remote docker supaya docker bisa berjalan di docker (docker in docker)
        - setup_remote_docker
        #install hadolint dan menjalankannya terhadap berkas dockerfile
        - run:
            name: "Lint Dockerfile"
            command: "docker run --rm --interactive hadolint/hadolint:latest < Dockerfile"
   #membuat job test-app
   test-app:
      docker:
        #menggunakan image cimg latest
        - image: "cimg/go:1.19.4"
      steps:
        #git branch checkout
        - checkout
        #menjalankan unit test untuk backend
        - run:
            name: "Menjalankan unit test untuk backend"
            command: "go test -v -short --count=1 $(go list ./...)"
   #membuat job build-app-karsajobs
   build-app-karsajobs:
      docker:
        #menggunakan docker image latest
        - image: "docker:19.03.15"
      steps:
        #git branch checkout        
        - checkout
        #setup remote docker supaya docker bisa berjalan di docker (docker in docker)
        - setup_remote_docker
        #build image dari dockerfile
        - run:
            name: "Build Image"
            command: "docker build . -t ghcr.io/tiosetiaatih/karsajobs:latest"
        - run:
        #Login GitHub Packages
            name: "Login GitHub Packages"
            command: "docker login ghcr.io -u $GITHUB_USERNAME -p $GITHUB_PASSWORD"
        #Push image ke GitHub Packages
        - run:
            name: "Pushing Image"
            command: "docker push ghcr.io/tiosetiaatih/karsajobs:latest"

workflows:
  #job yang di define lint-dockerfile, test-app, dan build-app-karsajobs (build dan push image)
  lint-test-build-push-workflow:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs